[package]
name = "alive-dsl"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
description = "nuclei-compatible DSL expression evaluator for matchers and extractors."

[dependencies]
evalexpr = { workspace = true }
regex = { workspace = true }
md-5 = { workspace = true }
sha1 = { workspace = true }
sha2 = { workspace = true }
hex = { workspace = true }
base64 = { workspace = true }
urlencoding = { workspace = true }
